# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c2c9627bcb1ffa5fb862a7a40226b14a1b47ae1b646c347cc187c490576e1ea1bf86bb2a7deff1b28d3a42e78fc3e79754011569983e3454dbcef59005b4dc49

test:
  secret_key_base: d3c81b91a8caefb8fb0c0808c41eb41a2c6942cda949ff29572c2bc730ad141e8e3c40187db2996db1b1f4fb694307a30278f55ffe7a86a2a4569f588ede48ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
